import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('branchline', {
  chooseRepository: () => ipcRenderer.invoke('repo:choose'),
  listRepositories: () => ipcRenderer.invoke('repo:list'),
  saveRepository: (repoPath: string) => ipcRenderer.invoke('repo:save', repoPath),
  removeRepository: (repoPath: string) => ipcRenderer.invoke('repo:remove', repoPath),
  inspectRepository: (repoPath: string) => ipcRenderer.invoke('repo:inspect', repoPath),
  getHistory: (repoPath: string, limit = 50, skip = 0, search = '') => ipcRenderer.invoke('repo:history', repoPath, limit, skip, search),
  getStashes: (repoPath: string) => ipcRenderer.invoke('repo:stashes', repoPath),
  getCommitDetails: (repoPath: string, commitId: string) => ipcRenderer.invoke('repo:commit-details', repoPath, commitId),
  getCommitDiff: (repoPath: string, commitId: string, filePath: string) => ipcRenderer.invoke('repo:commit-diff', repoPath, commitId, filePath),
  getBranches: (repoPath: string) => ipcRenderer.invoke('repo:branches', repoPath),
  getMergePreview: (repoPath: string, source: string) => ipcRenderer.invoke('repo:merge-preview', repoPath, source),
  getGitHubStatus: (repoPath: string) => ipcRenderer.invoke('github:status', repoPath),
  connectGitHub: (token: string) => ipcRenderer.invoke('github:connect', token),
  disconnectGitHub: () => ipcRenderer.invoke('github:disconnect'),
  getGitHubPullRequests: (repoPath: string, state: 'open' | 'closed' | 'all', page: number) => ipcRenderer.invoke('github:pull-requests', repoPath, state, page),
  getGitHubPullRequestBranches: (repoPath: string) => ipcRenderer.invoke('github:pull-request-branches', repoPath),
  createGitHubPullRequest: (repoPath: string, input: { title: string; body: string; head: string; base: string; draft: boolean }) => ipcRenderer.invoke('github:create-pull-request', repoPath, input),
  getGitHubActivity: (repoPath: string, page: number) => ipcRenderer.invoke('github:activity', repoPath, page),
  getGitHubPullRequestDetails: (repoPath: string, pullNumber: number) => ipcRenderer.invoke('github:pull-request-details', repoPath, pullNumber),
  getGitHubPullRequestReadiness: (repoPath: string, pullNumber: number) => ipcRenderer.invoke('github:pull-request-readiness', repoPath, pullNumber),
  getGitHubPullRequestMergeOptions: (repoPath: string, pullNumber: number) => ipcRenderer.invoke('github:pull-request-merge-options', repoPath, pullNumber),
  mergeGitHubPullRequest: (repoPath: string, pullNumber: number, method: 'merge' | 'squash' | 'rebase') => ipcRenderer.invoke('github:merge-pull-request', repoPath, pullNumber, method),
  getGitHubPullRequestMergeResult: (repoPath: string, pullNumber: number, uuid: string | null) => ipcRenderer.invoke('github:pull-request-merge-result', repoPath, pullNumber, uuid),
  getGitHubPullRequestSection: (repoPath: string, pullNumber: number, section: string, page: number) => ipcRenderer.invoke('github:pull-request-section', repoPath, pullNumber, section, page),
  createGitHubPullRequestComment: (repoPath: string, pullNumber: number, body: string) => ipcRenderer.invoke('github:create-pull-request-comment', repoPath, pullNumber, body),
  submitGitHubPullRequestReview: (repoPath: string, pullNumber: number, event: 'COMMENT' | 'APPROVE' | 'REQUEST_CHANGES', body: string) => ipcRenderer.invoke('github:submit-pull-request-review', repoPath, pullNumber, event, body),
  createGitHubPullRequestInlineComment: (repoPath: string, pullNumber: number, filePath: string, line: number, side: 'LEFT' | 'RIGHT', body: string) => ipcRenderer.invoke('github:create-pull-request-inline-comment', repoPath, pullNumber, filePath, line, side, body),
  requestGitHubPullRequestReviewers: (repoPath: string, pullNumber: number, users: string[], teams: string[]) => ipcRenderer.invoke('github:request-pull-request-reviewers', repoPath, pullNumber, users, teams),
  getGitHubPullRequestChecks: (repoPath: string, pullNumber: number) => ipcRenderer.invoke('github:pull-request-checks', repoPath, pullNumber),
  openGitHubUrl: (url: string) => ipcRenderer.invoke('github:open-url', url),
  getDiff: (repoPath: string, options: unknown) => ipcRenderer.invoke('repo:diff', repoPath, options),
  getOperations: (repoPath: string) => ipcRenderer.invoke('repo:operations', repoPath),
  operateGit: (repoPath: string, operation: unknown) => ipcRenderer.invoke('git:operate', repoPath, operation)
});
